version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./app:/usr/src/app
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    networks:
      - internal_network
  ngrok:
    image: ngrok/ngrok:latest
    command: ["http", "app:3000"]
    ports:
      - "4040:4040"
    depends_on:
      - app
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    networks:
      - internal_network
networks:
  internal_network:
    driver: bridge