services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./app:/usr/src/app
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    networks:
      - internal_network

  tunnel:
    build:
      context: ./docker/tunnel
      dockerfile: Dockerfile
    environment:
      - TARGET_HOST=app
      - TARGET_PORT=3000
      - TUNNEL_SUBDOMAIN=${TUNNEL_SUBDOMAIN:-random}
    restart: unless-stopped
    depends_on:
      - app
    networks:
      - internal_network
    env_file:
      - ./app/.env

networks:
  internal_network:
    driver: bridge